export const actionTypes = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILED: "SIGNUP_FAILED",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  // Ticket 
  
  CREATE_TICKET_REQUEST: "CREATE_TICKET_REQUEST",
  CREATE_TICKET_SUCCESS: "CREATE_TICKET_SUCCESS",
  CREATE_TICKET_FAILED: "CREATE_TICKET_FAILED",

  GET_TICKETS_REQUEST: "GET_TICKETS_REQUEST",
  GET_TICKETS_SUCCESS: "GET_TICKETS_SUCCESS",
  GET_TICKETS_FAILED: "GET_TICKETS_FAILED",

  GET_TICKET_BY_ID_REQUEST: "GET_TICKET_BY_ID_REQUEST",
  GET_TICKET_BY_ID_SUCCESS: "GET_TICKET_BY_ID_SUCCESS",
  GET_TICKET_BY_ID_FAILED: "GET_TICKET_BY_ID_FAILED",

  UPDATE_TICKET_REQUEST: "UPDATE_TICKET_REQUEST",
  UPDATE_TICKET_SUCCESS: "UPDATE_TICKET_SUCCESS",
  UPDATE_TICKET_FAILED: "UPDATE_TICKET_FAILED",

  CLOSED_TICKET_REQUEST: "CLOSED_TICKET_REQUEST",
  CLOSED_TICKET_SUCCESS: "CLOSED_TICKET_SUCCESS",
  CLOSED_TICKET_FAILED: "CLOSED_TICKET_FAILED",

  DELETE_TICKET_REQUEST: "DELETE_TICKET_REQUEST",
  DELETE_TICKET_SUCCESS: "DELETE_TICKET_SUCCESS",
  DELETE_TICKET_FAILED: "DELETE_TICKET_FAILED",

  UPDATE_PROPERTY: "UPDATE_PROPERTY",
};
